const ONE_DAY_OF_MINUTES = 24 * 60
const SOMEWHERE_HOUR = 16
const SOMEWHERE_MINUTES = 20
const SOMEWHERE_TIME_MINUTES = (SOMEWHERE_HOUR * 60) + SOMEWHERE_MINUTES
const SOMEWHERE_TIME_ENGLISH = '420'

module.exports = {
  ONE_DAY_OF_MINUTES,
  SOMEWHERE_HOUR,
  SOMEWHERE_MINUTES,
  SOMEWHERE_TIME_MINUTES,
  SOMEWHERE_TIME_ENGLISH,
}